[package]
name = "allelua"
version = "0.1.0"
edition = "2024"
license-file = "LICENSE"
description = "LuaJIT distribution blessed by programming gods."
documentation = "https://docs.rs/allelua"
repository = "https://github.com/negrel/allelua"
readme = "README.md"
authors = ["Alexandre Negrel <alexandre@negrel.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
