[package]
name = "allelua"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
description = "Lua distribution blessed by the gods of programming."
documentation = "https://docs.rs/allelua"
repository = "https://github.com/negrel/allelua"
readme = "README.md"
authors = ["Alexandre Negrel <alexandre@negrel.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "allelua"
path = "src/bin/allelua/main.rs"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
kanal = "0.1.0-pre8"
# console-subscriber = { version = "0.4.0" }
mlua = { version = "0.9", features = ["luajit52", "async"] }
tokio = { version = "1", features = ["time", "rt", "macros", "sync"] }
