[package]
name = "luatypes"
version = "0.1.0"
edition = "2021"

[dependencies]
full_moon = { version = "1.2.0", default-features = false, features = [
	"lua52",
	"luajit",
] }
smol_str = "0.3.2"
thiserror = "2.0.11"
